# ============================================================
# namespace.yaml
# Création du namespace icgroup
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: icgroup
  labels:
    env: prod
