# ============================================================
# hosts.ini - Inventaire Ansible IC GROUP
# Remplacez les IPs par vos vraies adresses quand les VMs
# seront créées
# ============================================================

[jenkins]
192.168.109.130 ansible_user=webster123 ansible_connection=local

[webapp]
# IP du serveur Web+pgAdmin (à remplir quand la VM sera créée)
192.168.109.131 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[odoo]
# IP du serveur Odoo (à remplir quand la VM sera créée)
192.168.109.132 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[prod:children]
webapp
odoo

[all:vars]
ansible_python_interpreter=/usr/bin/python3
